[build]
  command = "echo 'No build needed'"
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-transform"
    X-Netlify-Transform = "none"

[[plugins]]
  package = "@netlify/plugin-disable-optimizations"
